{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactor",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactor-1.6.1.jar",
          "url": "kotlinx-coroutines-reactor-1.6.1.jar",
          "size": 36797,
          "sha512": "f0c3274c3f09e2fc80f1d9fa99fd5f6a5c804cac29e34d98d826ff1d85c798e0395fd1ce653a97aaf4a2c10e0821af09c3d1ecd7694566c5175ce3759060e94b",
          "sha256": "73b69caa8362d8b504a32e923453ebf9f7f90d2c93a8c916cfe85de7e87adf2a",
          "sha1": "0e005b8db35929f41bf48dfa37b53dd0cce1f33f",
          "md5": "3397d261b0376cbf34e4cc739dc2546f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactor-1.6.1.jar",
          "url": "kotlinx-coroutines-reactor-1.6.1.jar",
          "size": 36797,
          "sha512": "f0c3274c3f09e2fc80f1d9fa99fd5f6a5c804cac29e34d98d826ff1d85c798e0395fd1ce653a97aaf4a2c10e0821af09c3d1ecd7694566c5175ce3759060e94b",
          "sha256": "73b69caa8362d8b504a32e923453ebf9f7f90d2c93a8c916cfe85de7e87adf2a",
          "sha1": "0e005b8db35929f41bf48dfa37b53dd0cce1f33f",
          "md5": "3397d261b0376cbf34e4cc739dc2546f"
        }
      ]
    }
  ]
}
