{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-javafx",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-javafx-1.6.4.jar",
          "url": "kotlinx-coroutines-javafx-1.6.4.jar",
          "size": 20290,
          "sha512": "bfb2e73e0ee697e09e0fef7525e208d46e75809957fd1c5f02682421049c532cec85c6f21ebbd522ad53b1d848fdbf3fd6d8b6625291e17506ae888118be4717",
          "sha256": "21bd20e842732036eb99518734e17de71e90c700a59b48ab2df292747cb26481",
          "sha1": "1645969d07998f33140341213da793a92e56abb5",
          "md5": "e39223b83df8c291a4467b5affba2974"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-javafx-1.6.4.jar",
          "url": "kotlinx-coroutines-javafx-1.6.4.jar",
          "size": 20290,
          "sha512": "bfb2e73e0ee697e09e0fef7525e208d46e75809957fd1c5f02682421049c532cec85c6f21ebbd522ad53b1d848fdbf3fd6d8b6625291e17506ae888118be4717",
          "sha256": "21bd20e842732036eb99518734e17de71e90c700a59b48ab2df292747cb26481",
          "sha1": "1645969d07998f33140341213da793a92e56abb5",
          "md5": "e39223b83df8c291a4467b5affba2974"
        }
      ]
    }
  ]
}
