{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-rx3",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-rx3-1.6.1.jar",
          "url": "kotlinx-coroutines-rx3-1.6.1.jar",
          "size": 90773,
          "sha512": "73e63b6556ff1d9d89e590725e46a7d0c4b8e804fab3b221f552e75b66ab2bcbf8844f13caedb819b852f5d2898b7efa0aabc148f07fac6ea130dcf831ff7b40",
          "sha256": "5af6ed814e54e04c7743c3c1ed55fb4cd01701f23e9543e93e1b69c3f472a027",
          "sha1": "daf3aa76f2d7f11117bc33f3b54b50cf1257c7bf",
          "md5": "e9e127c146435083d8dea669a672c0d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-rx3-1.6.1.jar",
          "url": "kotlinx-coroutines-rx3-1.6.1.jar",
          "size": 90773,
          "sha512": "73e63b6556ff1d9d89e590725e46a7d0c4b8e804fab3b221f552e75b66ab2bcbf8844f13caedb819b852f5d2898b7efa0aabc148f07fac6ea130dcf831ff7b40",
          "sha256": "5af6ed814e54e04c7743c3c1ed55fb4cd01701f23e9543e93e1b69c3f472a027",
          "sha1": "daf3aa76f2d7f11117bc33f3b54b50cf1257c7bf",
          "md5": "e9e127c146435083d8dea669a672c0d7"
        }
      ]
    }
  ]
}
