{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging-guava",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.6.0.aar",
          "url": "room-paging-guava-2.6.0.aar",
          "size": 10871,
          "sha512": "6beaf018e2dbb1f268a6e1194972b79918d4b5156a150fb82f67446c9ee8bbd1bee83df7964090785742ba695fd3532c06b0a953fa78cce6626215740d30b98e",
          "sha256": "05c16b3a37d9b9240a99fb76b36f45870aa8ad1b05cade1614ea2010759b27eb",
          "sha1": "34402292430639136e206c8c6e8bc5c815cbb3cf",
          "md5": "e9d68db6ce1f150d2edd484d31a4123e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.6.0.aar",
          "url": "room-paging-guava-2.6.0.aar",
          "size": 10871,
          "sha512": "6beaf018e2dbb1f268a6e1194972b79918d4b5156a150fb82f67446c9ee8bbd1bee83df7964090785742ba695fd3532c06b0a953fa78cce6626215740d30b98e",
          "sha256": "05c16b3a37d9b9240a99fb76b36f45870aa8ad1b05cade1614ea2010759b27eb",
          "sha1": "34402292430639136e206c8c6e8bc5c815cbb3cf",
          "md5": "e9d68db6ce1f150d2edd484d31a4123e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.6.0-sources.jar",
          "url": "room-paging-guava-2.6.0-sources.jar",
          "size": 2853,
          "sha512": "c1427056704e91b65ddf57728a2ab37e4ec0caff2bab5d7071980cf56ad23794630eae9d565c253e618b4b1163d2a611cf043e9fc6dd145086aa3480ddaa5a52",
          "sha256": "97035384f46d95fb1c13a8511a4a9c4b5633d7efeeceec421c3c698ad0d2e5d3",
          "sha1": "4f074a4f9f26a1911dc6294eeaf490754fdbb9a8",
          "md5": "1a948d46aa044841bfcd563f66af5786"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-paging-guava is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-paging-guava-2.6.0-versionMetadata.json",
          "url": "room-paging-guava-2.6.0-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}