{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactive",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.6.1.jar",
          "url": "kotlinx-coroutines-reactive-1.6.1.jar",
          "size": 63657,
          "sha512": "e4701728bdb0a16e7ddb38dd07d9d04740f5566ea158e724930a7a3fba755328f22e0e51262c58c43a662ded099930162523001f516e3aa5d0bd783cba688f90",
          "sha256": "76a13e1813addf7ed91c21f4300d8de1596eafff5f78891cebe164ca02aff169",
          "sha1": "17b1099a85d5c3509b9441478a56b66d1b514139",
          "md5": "f1b0941ccb8a72f7550e44f0797acbee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.6.1.jar",
          "url": "kotlinx-coroutines-reactive-1.6.1.jar",
          "size": 63657,
          "sha512": "e4701728bdb0a16e7ddb38dd07d9d04740f5566ea158e724930a7a3fba755328f22e0e51262c58c43a662ded099930162523001f516e3aa5d0bd783cba688f90",
          "sha256": "76a13e1813addf7ed91c21f4300d8de1596eafff5f78891cebe164ca02aff169",
          "sha1": "17b1099a85d5c3509b9441478a56b66d1b514139",
          "md5": "f1b0941ccb8a72f7550e44f0797acbee"
        }
      ]
    }
  ]
}
