{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-javafx",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-javafx-1.6.1.jar",
          "url": "kotlinx-coroutines-javafx-1.6.1.jar",
          "size": 20326,
          "sha512": "405d46d3b2a09cc5e1eef9c918eea30eac7401b36b547509b96c93ac1bb0f0095de3b86b27d2cc26a40e9d4b670565b4fa0c569d8c9c20f92725e253ac7d8135",
          "sha256": "cb898beb969d6c2a16003eb3482849ea05056d85023b6290bf7f8fae3132930b",
          "sha1": "e4ca3dd2800b1d8b8bd4252618a6074b5f928014",
          "md5": "0ff240621a9da45e3fd078aa550134b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-javafx-1.6.1.jar",
          "url": "kotlinx-coroutines-javafx-1.6.1.jar",
          "size": 20326,
          "sha512": "405d46d3b2a09cc5e1eef9c918eea30eac7401b36b547509b96c93ac1bb0f0095de3b86b27d2cc26a40e9d4b670565b4fa0c569d8c9c20f92725e253ac7d8135",
          "sha256": "cb898beb969d6c2a16003eb3482849ea05056d85023b6290bf7f8fae3132930b",
          "sha1": "e4ca3dd2800b1d8b8bd4252618a6074b5f928014",
          "md5": "0ff240621a9da45e3fd078aa550134b3"
        }
      ]
    }
  ]
}
